/*
 * Copyright (c) 2026 Tylium.
 * SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-TELF
 * See LICENSE.md for details.
 */

/**
 * Application version number.
 * This file is automatically generated from package.json.
 * Do not edit manually - run `pnpm generate:version` or it will be updated automatically during build/dev.
 */

export const APP_VERSION_LABEL = "Developer Preview";
export const APP_VERSION = "1.0.0-dev";
