#!/usr/bin/env node

/*
 * Copyright (c) 2026 Tylium.
 * SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-TELF-1.0
 * See LICENSE.md for details.
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Generates version.ts file from package.json version and versionLabel.
 *
 * Reads the version and versionLabel fields from package.json and generates
 * a TypeScript file with exported constants for use in the application.
 * The generated file includes proper copyright headers and documentation
 * indicating it is auto-generated.
 *
 * @throws {Error} If version is not found in package.json
 */
function generateVersion() {
    const packageJsonPath = join(__dirname, "..", "package.json");
    const versionTsPath = join(__dirname, "..", "lib", "version.ts");

    // Read package.json
    const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
    const version = packageJson.version;
    const versionLabel = packageJson.versionLabel || "Version";

    if (!version) {
        throw new Error("Version not found in package.json");
    }

    // Generate version.ts content
    const content = `/*
 * Copyright (c) 2026 Tylium.
 * SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-TELF-1.0
 * See LICENSE.md for details.
 */

/**
 * Application version number.
 * This file is automatically generated from package.json.
 * Do not edit manually - run \`pnpm generate:version\` or it will be updated automatically during build/dev.
 */

export const APP_VERSION_LABEL = "${versionLabel}";
export const APP_VERSION = "${version}";
`;

    // Write version.ts
    writeFileSync(versionTsPath, content, "utf-8");
    console.log(`✓ Generated version.ts with version: ${version} (${versionLabel})`);
}

generateVersion();
