import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@cutoff/audio-ui-react/style.css";
import "./globals.css";
import {Providers} from "@/app/providers";
import SideBar from "@/components/SideBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Providers>
            <div className="flex h-screen">
                {/* SideBar will be client-side rendered */}
                <div className="h-screen">
                    <SideBar />
                </div>
                <div className="flex-1">
                    {children}
                </div>
            </div>
        </Providers>
        </body>
        </html>
    );
}
